version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: elections_scolaires_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: elections_scolaires
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: elections_scolaires_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

  api:
    build: ./api
    container_name: elections_scolaires_api
    environment:
      DATABASE_URL: postgresql://admin:admin123@postgres:5432/elections_scolaires
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: elections_scolaires_frontend
    environment:
      VITE_API_URL: http://localhost:8000
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  postgres_data: